default:
  image: node:22-slim
  cache:
    paths:
      - npm_cache
    key:
      files: [package-lock.json]
      prefix: v1

workflow:
  rules:
    - if: '$CI_PIPELINE_SOURCE == "push"'

build-lib:
  stage: build
  script:
    - rm "$NPM_TOKEN"
    - npm ci --cache npm_cache
    - npm run build
  artifacts:
    paths:
      - dist

run-tests:
  stage: test
  rules:
    - if: '$CI_COMMIT_BRANCH != "release"'
  script:
    - rm "$NPM_TOKEN"
    - apt update
    - apt install -y libgtk-3-0 libasound2 libx11-xcb-dev libnss3 libgbm-dev libdrm2
    - npm ci --cache npm_cache
    - npm test

lint:
  stage: test
  rules:
    - if: '$CI_COMMIT_BRANCH != "release"'
  script:
    - rm "$NPM_TOKEN"
    - npm ci --cache npm_cache
    - npm exec --no prettier -- --check .

pages:
  stage: deploy
  needs:
    - run-tests
  rules:
    - if: '$CI_COMMIT_BRANCH != "release"'
  script:
    - rm "$NPM_TOKEN"
    - apt update
    - apt-get install -y --no-install-recommends git brotli
    - npm ci --cache npm_cache
    - cd demo && npm exec --no vite -- build --base="./" && cd ..
    - find demo/dist -type f -regex '.*\.\(htm\|html\|txt\|text\|js\|css\)$' -exec gzip -f -k {} \;
    - find demo/dist -type f -regex '.*\.\(htm\|html\|txt\|text\|js\|css\)$' -exec brotli -f -k {} \;
  publish: demo/dist
  artifacts:
    paths:
      - demo/dist

publish:
  stage: deploy
  id_tokens:
    SIGSTORE_ID_TOKEN:
      aud: sigstore
  rules:
    - if: '$CI_COMMIT_BRANCH == "release"'
  script:
    - printf '//registry.npmjs.org/:_authToken=' > ~/.npmrc
    - cat "$NPM_TOKEN" >> ~/.npmrc
    - rm "$NPM_TOKEN"
    - npm publish --provenance
