default:
  image: node:24-slim
  cache:
    paths:
      - npm_cache
    key:
      files: [package-lock.json]
      prefix: v1

workflow:
  rules:
    - if: '$CI_PIPELINE_SOURCE == "push"'

build-lib:
  stage: build
  script:
    - npm ci --cache npm_cache
    - npm run build
  artifacts:
    paths:
      - dist

run-tests:
  stage: test
  rules:
    - if: "$CI_COMMIT_BRANCH"
  before_script:
    - apt update
    - apt install -y libgtk-3-0 libasound2 libx11-xcb-dev libnss3 libgbm-dev libdrm2 xz-utils
  script:
    - npm ci --cache npm_cache
    - npm test

lint:
  stage: test
  rules:
    - if: "$CI_COMMIT_BRANCH"
  script:
    - npm ci --cache npm_cache
    - npm exec --no prettier -- --check .

pages:
  stage: deploy
  needs:
    - run-tests
  rules:
    - if: "$CI_MERGE_REQUEST_ID"
      when: never
    - if: "$CI_COMMIT_BRANCH"
  before_script:
    - apt update
    - apt-get install -y --no-install-recommends git brotli
  script:
    - npm ci --cache npm_cache
    - cd demo && npm exec --no vite -- build --base="./" && cd ..
    - find demo/dist -type f -regex '.*\.\(htm\|html\|txt\|text\|js\|css\)$' -exec gzip -f -k {} \;
    - find demo/dist -type f -regex '.*\.\(htm\|html\|txt\|text\|js\|css\)$' -exec brotli -f -k {} \;
  publish: demo/dist
  artifacts:
    paths:
      - demo/dist

publish:
  stage: deploy
  id_tokens:
    NPM_ID_TOKEN:
      aud: "npm:registry.npmjs.org"
    SIGSTORE_ID_TOKEN:
      aud: sigstore
  rules:
    - if: '$CI_PROJECT_NAMESPACE != "_rvidal"'
      when: never
    - if: "$CI_COMMIT_TAG"
  script:
    - npm publish
